// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    return $.fn.zoomBox = function(options) {
      var $img, $zb, addEventListeners, getFullImageSrc, init, loadFullImage, modeChangeStart, modeChangeStop, moveImage, onMouseMove, readyToZoom, removeEventListeners, settings, startX, startY, toggleMode, trace, zoomOff, zoomOn;
      settings = $.extend({
        'dev': false,
        'clickToggle': true
      }, options);
      $zb = this;
      $img = null;
      startX = 0;
      startY = 0;
      trace = function(str) {
        if (settings.dev) {
          return console.info(str);
        }
      };
      toggleMode = function() {
        if ($zb.hasClass('zb-error')) {
          trace('cannot toggle; the image was not found!');
          return;
        }
        trace("zoom image toggle mode");
        if ($zb.hasClass('zb-zoom-on')) {
          return zoomOff();
        } else {
          return zoomOn();
        }
      };
      modeChangeStart = function() {
        return $zb.addClass('zb-processing');
      };
      modeChangeStop = function() {
        return $zb.removeClass('zb-processing');
      };
      zoomOff = function() {
        trace("zoom off");
        modeChangeStart();
        $zb.removeClass('zb-zoom-on');
        removeEventListeners();
        return modeChangeStop();
      };
      zoomOn = function() {
        trace("zoom on");
        modeChangeStart();
        if ($zb.hasClass('zb-loaded')) {
          return readyToZoom();
        } else {
          return loadFullImage(readyToZoom);
        }
      };
      readyToZoom = function() {
        trace("ready to zoom");
        addEventListeners();
        moveImage(startX, startY);
        return $zb.addClass('zb-zoom-on');
      };
      addEventListeners = function() {
        trace("add event listeners");
        return $zb.on("mousemove", onMouseMove);
      };
      removeEventListeners = function() {
        trace("remove event listeners");
        return $zb.off("mousemove", onMouseMove);
      };
      getFullImageSrc = function() {
        return $zb.data("zoom-src");
      };
      loadFullImage = function(callback) {
        var img, src;
        $zb.addClass("zb-loading");
        src = getFullImageSrc();
        trace("load full image " + src);
        img = new Image();
        img.onload = function() {
          trace("image load complete");
          $zb.removeClass("zb-loading");
          $zb.addClass("zb-loaded");
          $img = $('<img src="' + src + '" alt="" class="zb-full" />');
          $zb.append($img);
          if (typeof callback === "function") {
            return callback();
          }
        };
        img.onerror = function() {
          trace("cannot load image " + src);
          return $zb.addClass("zb-error");
        };
        return img.src = src;
      };
      onMouseMove = function(e) {
        return moveImage(e.pageX, e.pageY);
      };
      moveImage = function(mouseAbsoluteX, mouseAbsoluteY) {
        var boxH, boxW, imgH, imgW, mouseX, mouseY, myX, myY;
        if (!$img) {
          return;
        }
        mouseX = mouseAbsoluteX - $zb.offset().left;
        mouseY = mouseAbsoluteY - $zb.offset().top;
        imgW = $img.width();
        imgH = $img.height();
        boxW = $zb.width();
        boxH = $zb.height();
        if (boxW > imgW || boxH > imgH) {
          trace("full image can't be smaller then the box");
          return;
        }
        myX = mouseX / boxW * (imgW - boxW);
        myY = mouseY / boxH * (imgH - boxH);
        $img.css("left", -myX + "px");
        return $img.css("top", -myY + "px");
      };
      $.fn.zoomBox.toggle = function() {
        return toggleMode();
      };
      if (settings.clickToggle) {
        $zb.on("click", function(e) {
          e.preventDefault();
          startX = e.pageX - $zb.offset().left;
          startY = e.pageY - $zb.offset().top;
          return toggleMode();
        });
      }
      init = function() {
        return trace("ZoomBox!");
      };
      return init();
    };
  })(jQuery);

}).call(this);
